[package]
name = "async_tut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
queues = "1.0.2"
tokio = { features = ["full"] }

[dependencies.timer_future]
path = "../timer_future"